opts: NormalizeCapability(): fix redefinition of the built-in function (revive)
    opts/capabilities.go:25:2: redefines-builtin-id: redefinition of the built-in function cap (revive)
        cap = strings.ToUpper(strings.TrimSpace(cap))
        ^
    opts/capabilities.go:30:3: redefines-builtin-id: redefinition of the built-in function cap (revive)
            cap = "CAP_" + cap
            ^

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
(cherry picked from commit f5fad186c081dcbd77d45a5e9d4eb295e87028d9)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>