Update system_prune.md
Added comment because this looks like it should work but doesn't
> docker system prune --force --all --volumes --filter "until=36h"
ERROR: The "until" filter is not supported with "--volumes"